### ISSUE TITLE
Lỗi cài NukeViet eGovernment bước 6

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/eGovernment#1]
Cài NukeViet eGovernment tới bước 6 báo lỗi 

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'

Thông tin máy chủ

> - Phiên bản NukeViet eGovernment: (nhánh master)
> - Môi trường thử Nghiệm: Localhost
> - Hệ điều hành: Windown 10
> - Trình duyệt web: Google Chrome
> - Máy chủ web: XAMPP v3.2.2

**Comment by vuthao** [comment]
@nambmtk1993 thử debug xem, chứ anh cài trên 3 máy chưa thấy lỗi.
