### ISSUE TITLE
Cơ sở dữ liệu mẫu bị chèn quảng cáo

### ISSUE THREAD

**Issue by thehung** [nukeviet/eGovernment#11]
Kiểm tra lại trong Cơ sở dữ liệu mẫu còn sót quảng cáo trong quá trình copi từ bài viết gốc. Ví dụ bài này: /news/thong-tin-tuyen-truyen/diem-mat-9-nham-lan-thuong-gap-ve-phan-mem-nguon-mo-5.html

**Comment by vuthao** [comment]
Lỗi này đã được sủa, và sẽ được câp nhật vào phiên bản phát hành tới.
