### ISSUE TITLE
Lỗi khi thêm chuyên mục mới của module tin tức

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/eGovernment#12]
- Lỗi trắng trang khi thêm chuyên mục mới của tin tức. 
- F5 lại thấy chuyên mục mới đó nhưng chuyên mục đó từ đâu mọc ra các bài viết mặc dù chưa thêm bài mới naod

**Comment by vuthao** [comment]
Lỗi này là lỗi chung của NukeViet  mình đã fix lại.
