### ISSUE TITLE
Dung lượng tải file đóng về quá lớn

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/eGovernment#13]
Dung lượng tải về file đóng gói eGovernment quá lớn khoảng 22MB. Nguyên nhân do các ảnh trong thư mục upload mặc định của NukeViet CMS chưa được xóa trong NukeViet eGovernment

**Comment by vuthao** [comment]
Hiện tại đã xóa vợi file không dùng đến nữa.
