### ISSUE TITLE
Lỗi tìm kiếm trên menu kg hoạt động

### ISSUE THREAD

**Issue by anhutbeo** [nukeviet/eGovernment#14]
Lick vào biểu tượng tìm kiếm trên menu rồi tìm nhưng nó kg hoạt động

**Comment by hoanglongvnpt** [comment]
Sao chưa thấy pix lỗi nhể?

**Comment by vuthao** [comment]
Lỗi này đã được sủa, và sẽ được câp nhật vào phiên bản phát hành tới.
