### ISSUE TITLE
Tên site sau khi cài đặt xong không giống với tên đã khai báo khi cài đặt

### ISSUE THREAD

**Issue by thehung** [nukeviet/eGovernment#16]
Tên site được khai báo khi cài đặt không chuyển vào đúng các chỗ cần thiết (Banner, Footer ngoài site, footer Admin Control Panel, trong phần cấu hình site)

**Comment by ngocphan123** [comment]
Em check không thấy lỗi này ạ

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/0e8e7f6a477882156509f9b2387fbd9caea0e5d2

**Comment by thehung** [comment]
Bản 97ebba4c60206b30918d03dda17b6a554b27c0a9 lại dính lỗi này!
