### ISSUE TITLE
Thay đổi chiều cao khối quảng cáo trong module quảng cáo

### ISSUE THREAD

**Issue by motcaitenit38** [nukeviet/eGovernment#17]
Sau khi vào thay đổi kích thước (cụ thể là chiều cao) của khối quảng cáo trong module quảng cáo thì web không nhận chiều cao mới, mà vẫn chạy chiều cao cũ, cho dù đã báo thay đổi thành công.

**Comment by ngocphan123** [comment]
Bạn xem lại lỗi này mình check không thấy lỗi

**Comment by thuvp1995** [comment]
lỗi này đã được fix
