### ISSUE TITLE
Vẫn tồn tại value "egov.nukeviet.dev" trong cấu hình chung của site sau khi cài đặt mẫu

### ISSUE THREAD

**Issue by webvangvn** [nukeviet/eGovernment#24]
![loi-my-domain](https://user-images.githubusercontent.com/8604866/30854093-e2f4639a-a2da-11e7-948c-c0fc540b7963.jpg)

Kết thúc quá trình cài đặt , vào cấu hình chung vẫn chưa được thay đổi theo domain chạy cài đặt . Nó vẫn giữ nguyên giá trị so với dữ liệu mẫu.

**Comment by vuthao** [comment]
Mình đã sửa lỗi này và sẽ cập nhật trong bản phát hành tới
