### ISSUE TITLE
Góp ý về module Cơ cấu tổ chức trong phiên bản GOV

### ISSUE THREAD

**Issue by hpleduit** [nukeviet/eGovernment#26]
Chào mọi người
Mình đã sử dụng thử phiên bản này chưa thấy phát sinh lỗi nào nghiêm trọng; tuy nhiên mình dùng phiên bản này có module **Cơ cấu tổ chức** và đã cài đặt dữ liệu mẫu lên mình cũng đang làm trong trường học vì vậy mình thấy có bất cập chổ **Tổ chức đoàn** thể vì trong 1 cơ quan đơn vị anh có thể có nhiều vị trí và vai trò lãnh đạo khác nhau Ví dụ: 1 người là Hiệu trưởng (Thủ trưởng cơ quan) thì có thể giữ chức vụ tại Thuộc tổ chức, cơ sở (Ban giám hiệu) và còn giữ chức thêm tại Thuộc tổ chức, cơ sở khác  đó là Bí thư của một Đảng bộ( Chi bộ) của cơ quan đó.
Vì vậy theo mình nghĩ ở phần mục thêm nhân sự nên để mục **Thuộc tổ chức, cơ sở** thành check box giống phần chuyên mục trong module tin tức chẳng hạn thay Select box đơn như hiện tại.
Trân trọng cảm ơn.

**Comment by thehung** [comment]
Cảm ơn bạn,

Xin ghi nhận ý kiến sang đây để xử lý: https://github.com/nukeviet/module-organs/issues/1
