### ISSUE TITLE
Lỗi giao diện tại phần xem chi tiết văn bản như hình đính kèm

### ISSUE THREAD

**Issue by hpleduit** [nukeviet/eGovernment#28]
Trên trình duyệt firefox Banner chính bị đẩy xuống dưới đè menu chính trong phần xem chi tiết văn bản http://egov-demo.nukeviet.vn/laws/detail/Cong-van-so-4622-BGDDT-CNTT-ve-viec-huong-dan-thuc-hien-nhiem-vu-CNTT-nam-hoc-2016-2017-1/ , có thể xem chi tiết tại hình đính kèm.  Các trình duyệt web khác lại không bị.
Banner chính khi ở chuyên mục chính http://egov-demo.nukeviet.vn/laws/ thì không bị đẩy xuống không ảnh hưởng gì hết.
Mình kiểm tra nhiều lần nhưng không thể xác định được.
Mọi người có gặp lổi này không? mong mọi người hướng dẫn giúp. Cảm ơn.
![xem chi tiet laws](https://user-images.githubusercontent.com/4101710/31267174-61a50ff0-aaa1-11e7-934f-46e43f4db843.jpg)

**Comment by thehung** [comment]
Xác nhận có lỗi này trên demo!

**Comment by vuthao** [comment]
Lỗi này có bị trên FF, Chrome không bị nhé @thuvp1995

**Comment by thuvp1995** [comment]
Lỗi này đã được fix
