### ISSUE TITLE
Lỗi sau khi cài đặt

### ISSUE THREAD

**Issue by thehung** [nukeviet/eGovernment#3]
Bản mới nhất tại thời điểm báo lỗi.
Môi trường test: Localhost + Windows 10 + FireFox 54 + Vertrigo 2.46
Quá trình cài đặt không chọn cài Cơ sở dữ liệu mẫu hoặc cài Cơ sở dữ liệu mẫu đều gặp lỗi: Click link đăng nhập Admin Control Panel hoặc ra trang chính thì đều nhận được báo lỗi "Session object not supported"

**Comment by vuthao** [comment]
@thehung tạm thời xóa đoạn sau đi:
```php
if (empty($ini_list['session.save_handler']) or empty($ini_list['session.save_path'])) {
    die('Session object not supported');
}
```
Đoạn này cuối file includes/ini.php

**Comment by thehung** [comment]
Kết quả là bị trắng trang @vuthao

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/eGovernment/commit/f8afab9bf19978215939414b9ee3f951b3d5c8db
