### ISSUE TITLE
Lỗi sai link so với phần tên "liên kết"

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/eGovernment#31]
Ở dữ liệu demo sau khi cài xong thì phần "Liên kết" ở trên topbar trên cùng bên phải site có link trỏ đến thông báo.
Tiêu đề với link không đúng cần điều chỉnh lại cho hợp lý
Tiêu đề "Liên kết"
![image](https://user-images.githubusercontent.com/13896524/31490383-ea7c58d0-af6d-11e7-8634-46bd35ee792a.png)
Link: .../page/thong-bao.html
![image](https://user-images.githubusercontent.com/13896524/31490393-f7141010-af6d-11e7-94ae-2efa139a8169.png)

**Comment by thehung** [comment]
Đó là trang hướng dẫn cho người sử dụng cài module hoặc tạo trang liên kết mà!

**Comment by ThinhNguyenVB** [comment]
@thehung theo em thì để title là thông báo thay vì chữ liên kết

**Comment by thehung** [comment]
Chỗ đó dành đặt link đến trang "liên kết". Em đọc nội dung thông báo sẽ hiểu!

**Comment by ThinhNguyenVB** [comment]
@thehung vâng
