### ISSUE TITLE
Lỗi link alias ở module ảo about của page

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/eGovernment#32]
Khi đổi lại link của bài giới thiệu chung như hình:

![image](https://user-images.githubusercontent.com/13896524/31490490-5167831c-af6e-11e7-920b-b785c0ad5279.png)

thì ở link cũ truy cập sẽ lỗi: /about/Gioi-thieu-chung.html
thành trống không mà đúng ra là phải ra trang 404.

![image](https://user-images.githubusercontent.com/13896524/31490536-795eb3e0-af6e-11e7-9305-54232f86e838.png)

Xampp 5.6.19 trên windows
Lưu ý, điền bất kỳ tên url là gì của about đêu ra trống

**Comment by vuthao** [comment]
@ThinhNguyenVB hi truy cập link không tồn tại nó chuyển về trang chủ của module đó.
Và module này được cấu hình hiển thị 1 bài viết chính nên thế
