### ISSUE TITLE
Lỗi giao diện khi truy cập link bộ phận của module contact

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/eGovernment#33]
Khi truy cập link bộ phận ngay từ trong trang admin của module liên hệ ra ngoài site ví dụ: http://egov.in/contact/ban-bien-tap/0/ của "Ban biên tập Cổng thông tin điện tử UBND thành phố" bị lỗi bể giao diện

![image](https://user-images.githubusercontent.com/13896524/31491481-acf1d3f6-af71-11e7-8ecb-94a6689480bf.png)

**Comment by thehung** [comment]
Không phải lỗi bể giao diện mà đây là một tính năng của module contact (sử
dụng để chèn form liên hệ tới một bộ phận cụ thể vào frame). chỉ số 0 ở URL
biểu thị việc không hiển thị header, fotter và các block, số 1 là có hiển
thị!

**Comment by ThinhNguyenVB** [comment]
@thehung để vậy hơi kì cục, frame cho block hiện ở vị trí trên themes thì hợp lý hơn thay vì để kiểu vậy anh ạ. Chứ như này không ổn

**Comment by thehung** [comment]
Cái này của NukeViet chứ không phải của riêng bản eGovernment.
Chưa rõ ý đồ lại sao đặt link đó vào trong trang quản trị :-)

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/nukeviet/nukeviet/commit/5a924481c18c1c07fa9aef9c3cdeca837fc98033
