### ISSUE TITLE
Lỗi gõ thừa url ở module feed, laws và organs vẫn hiện nội dung như bình thường

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/eGovernment#34]
Hiện tại đối với module laws gặp tình trạng như sau

Khi truy cập: http://egov.in/laws/121212121/ vẫn hiển thị nội dung trang main dù url này không tồn tại

Truy cập: http://egov.in/laws/detail/Cong-van-so-4622-BGDDT-CNTT-ve-viec-huong-dan-thuc-hien-nhiem-vu-CNTT-nam-hoc-2016-2017-1/12121/ vẫn hiển thị nội dung trang của công văn đó.

Truy cập http://egov.in/laws/Cong-van/12121212/ thì vẫn ra mục công văn

Với module feed khi truy cập link http://egov.in/feeds/21212/ vẫn ra module đó

Với module organs cũng tương tự như trên (module ảo của nó là cơ cấu tổ chức)

3 module này mắc lỗi điều hướng url, url không tồn tại thì phải ra 404 thay vì nội dung hiển thị

**Comment by hoaquynhtim99** [comment]
Fixed: 
https://github.com/hoaquynhtim99/nukeviet/commit/61de32a2dbe3dd958e13fc8bfe1dc51d3ff6fddd
https://github.com/nukeviet/module-organs/commit/7993d43f47279249428f54e08a648278c74feea0
https://github.com/nukeviet/module-laws/commit/fa2e72ebd0b850475c2c93c4ea6b91104764eade
