### ISSUE TITLE
Lỗi trang chủ chuyển hướng quá nhiều lần khi thử nghiệm trên localhost

### ISSUE THREAD

**Issue by thehung** [nukeviet/eGovernment#37]
Phiên bản: 1.0.02
Môi trường test: Localhost + Windows 10 + FireFox 56.0.1 + Vertrigo 2.46
Lỗi như hình dưới
![anh-chup-44](https://user-images.githubusercontent.com/1892900/31508115-4852c5dc-afa7-11e7-9762-830f5f0f0280.jpg)
Admin Control Panel vẫn truy cập được bình thường!
Đã thử trên các trình duyệt: FireFox, Chrome, Opera mới nhất!

**Comment by hoanglongvnpt** [comment]
Phiên bản: 1.0.03
Môi trường test: Localhost + Windows 8 + chrom Phiên bản 61.0.3163.100
Lỗi như hình dưới
![egov](https://user-images.githubusercontent.com/11238423/31527784-d32fcf4a-aff9-11e7-9690-757b1ea28af7.png)

**Comment by hpleduit** [comment]
Lỗi như demo của các anh. Nếu chạy lên thì tất cả các trang khác cũng không load được khi tắt trang này đi thì các trang khác hoạt động bình thường trở lại.
Nếu vào cài đặt chế độ ngôn ngữ "Loại bỏ kí tự ngôn ngữ trên url" thì chạy không có vấn đề gì hết.
localhost/tenthumuc/vi/ thì OK.

**Comment by hoaquynhtim99** [comment]
Phần này đã được fix ở bản NukeViet 4.3
