### ISSUE TITLE
Lỗi trang chủ chuyển hướng quá nhiều lần

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/eGovernment#38]
Phiên bản: 1.0.03
Môi trường test: Localhost + Windows 8 + chrom Phiên bản 61.0.3163.100
Lỗi như hình dưới
![egov](https://user-images.githubusercontent.com/11238423/31527861-2ccd8876-affa-11e7-976e-d8b6d7afc07a.png)
Vào admin vẫn bình thường

**Comment by thehung** [comment]
Lỗi đã được báo ở đây: https://github.com/nukeviet/eGovernment/issues/37

**Comment by thehung** [comment]
Bản tối qua là 1.0.02 (1.0 beta 3)

**Comment by hoanglongvnpt** [comment]
mắt mũi dạo này lèm nhèm quá roài....

**Comment by hoanglongvnpt** [comment]
Sao chưa thấy hồi âm nhể?
