### ISSUE TITLE
Góp ý giao diện

### ISSUE THREAD

**Issue by ngoctu2008** [nukeviet/eGovernment#39]
Phần banner của giao diện nên sử dụng theo website http://qh-hdnd.phuyen.gov.vn

**Comment by thehung** [comment]
Mình thấy cái banner site qh-hdnd.phuyen.gov.vn nặng nề và không đẹp!

**Comment by vuthao** [comment]
Giao diện mỗi người mối ý, đẹp xấu tùy từng con mắt.
Do đó theo mình ai thích như thế nào sẽ sửa thế ấy là tốt nhất
