### ISSUE TITLE
Logo cài đặt vẫn là logo của NukeViet CMS

### ISSUE THREAD

**Issue by thehung** [nukeviet/eGovernment#4]
Cần sửa thành logo của NukeViet eGovernment

**Comment by vuthao** [comment]
Thực hiện xong: https://github.com/nukeviet/eGovernment/commit/72b3358a9c324740da8e00952d7dc89ef3f32d1f

**Comment by thehung** [comment]
Kiểm tra trên revision mới nhất vẫn là logo NukeViet CMS
