### ISSUE TITLE
Lỗi cài đặt

### ISSUE THREAD

**Issue by ngocphan123** [nukeviet/eGovernment#40]
Khi cài đặt đến bước 6 và nhập câu hỏi bảo mật và câu trả lời của bạn chỉ có 1 ký tự thì hệ thống không thông báo lỗi mà trở về bước 2, cài đặt trên trình duyệt chomre và php 5.6 dưới local.

**Comment by vuthao** [comment]
Mình kiểm tra thì không bị lỗi như @ngocphan123 báo.

**Comment by thehung** [comment]
@ngocphan123 check lại, nếu không có lỗi thì đóng issue nhé!
