### ISSUE TITLE
Module opinions không hiển thị form góp ý cho guest, chỉ hiển thị cho member

### ISSUE THREAD

**Issue by thehung** [nukeviet/eGovernment#43]
Phiên bản: 1.0.03
Môi trường test: Localhost + Windows 10 + FireFox 56.0.1 + Vertrigo 2.46
Module opinions không hiển thị form góp ý cho guest, chỉ hiển thị cho member mặc dù cấu hình đã được thiết lập là "Tất cả" được phép đăng bình luận.

**Comment by hoaquynhtim99** [comment]
@thehung anh xem bản mới nhất còn cái này không nhé

**Comment by hungattok57** [comment]
@thehung Em kiểm tra lại thì thấy như sau:
Trong phiên bản 1.0.03
Nếu cấu hình thiết lập là "Theo cấu hình bài viết" và tích thêm cả phần "Tất cả" thì guest sẽ không bình luận được còn nếu thiết lập chỉ tích vào "Tất cả" thôi thì guest sẽ bình luận được.

**Comment by hoaquynhtim99** [comment]
@hungattok57 mình đã kiểm tra lại, có lỗi như tiêu đề của Issue này: "Chỉ hiển thị cho member" đúng ra là chỉ hiển thị cho điều hành chung trở lên và đã sửa tại https://github.com/nukeviet/module-laws/commit/b3bd4027fba43cf3d5e3b95c652c1ad3043fc788

Còn bài số 5 và số 7 không hiển thị form lấy ý kiến cho Guest là chính xác bởi nó đã hết thời hạn lấy ý kiến.

**Comment by hungattok57** [comment]
@hoaquynhtim99 
Vậy thì hết lỗi rồi anh ạ
