### ISSUE TITLE
Lỗi: Mất hình minh họa tại phần thiết lập giao diện khi không cài site ở webroot

### ISSUE THREAD

**Issue by thehung** [nukeviet/eGovernment#44]
Phiên bản: 1.0.03
Môi trường test: Localhost + Windows 10 + FireFox 56.0.1 + Vertrigo 2.46
Thư mục cài: http://localhost/nukeviet-egov/
Lỗi: Mất hình minh họa tại phần thiết lập giao diện
![anh-chup-46](https://user-images.githubusercontent.com/1892900/31785994-28540f90-b531-11e7-9242-1bbbab8307a3.jpg)

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/eGovernment/commit/7551aa7d74463461aae502ea976b1310020a6f17
