### ISSUE TITLE
Lỗi rất rất nghiệm trọng khi đăng nhập

### ISSUE THREAD

**Issue by quangluutk** [nukeviet/eGovernment#53]
Đăng nhập được vào admin với tài khoản và một mật khẩu bất kỳ. 
Mong admin kiểm tra và sữa lỗi gấp!

**Comment by vuthao** [comment]
Cám ơn @quangluutk đã thông báo.

Bạn có thể copy lại file: includes/core/admin_login.php từ https://raw.githubusercontent.com/nukeviet/eGovernment/master/includes/core/admin_login.php

**Comment by quangluutk** [comment]
Cảm ơn anh Thảo!
