### ISSUE TITLE
Nên hay không nên lặp lại tiêu để trong module Quản lý cán bộ

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/eGovernment#58]
Mình thấy tiêu đề danh mục Tổ chức bị lặp lại 2 lần. Vậy nên hay không nên?
Những vị trí khoanh tròn màu đen theo mình nên bỏ thì đẹp hơn. Góp ý nhỏ.
![899](https://user-images.githubusercontent.com/11238423/32475745-f9d6d516-c3a5-11e7-9341-e80c69d1f4b1.png)

**Comment by hoaquynhtim99** [comment]
Mình đã cho ẩn theo commit này https://github.com/nukeviet/module-organs/commit/c9a27deda17f5cb37f994b2f53362d7784a1f3c7
