### ISSUE TITLE
Góp ý: Lỗi giao diện module news (Mặc định 2 cột)

### ISSUE THREAD

**Issue by ngoctu2008** [nukeviet/eGovernment#59]
![image](https://user-images.githubusercontent.com/9164986/32695600-bd0f5b80-c792-11e7-9f96-647d3b181d30.png)
trong file style.css của theme egov:
`.height-hometext:after {
    position: absolute;
    bottom: 44px;
    **height: 20px;**
    width: 93%;
    content: '';
    background: -moz-linear-gradient(left, rgba(255,255,255,0.6) 0%, rgba(255,255,255,0.6) 100%); /* FF3.6+ */
    background: -webkit-gradient(linear, left top, right top, color-stop(0%,rgba(255,255,255,0.6)), color-stop(100%,rgba(255,255,255,0.6))); /* Chrome,Safari4+ */
    background: -webkit-linear-gradient(left, rgba(255,255,255,0.6) 0%,rgba(255,255,255,0.6) 100%); /* Chrome10+,Safari5.1+ */
    background: -o-linear-gradient(left, rgba(255,255,255,0.6) 0%,rgba(255,255,255,0.6) 100%); /* Opera 11.10+ */
    background: -ms-linear-gradient(left, rgba(255,255,255,0.6) 0%,rgba(255,255,255,0.6) 100%); /* IE10+ */
    background: linear-gradient(left, rgba(255,255,255,0.6) 0%,rgba(255,255,255,0.6) 100%); /* W3C */
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#00ffffff', endColorstr='#ffffff',GradientType=1 );
}`

Bỏ  **height: 20px;**

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/eGovernment/commit/d0fdbbaddde069916e58a9b20d4badc8f30f74c8
