### ISSUE TITLE
Lỗi khi kích vào quảng cáo

### ISSUE THREAD

**Issue by ngocphan123** [nukeviet/eGovernment#60]
Khi kích vào góp ý của dân và lấy ý kiến dự thảo văn bản như hình gây lỗi truy cập 404(Cài đặt trên bản releases : https://github.com/nukeviet/eGovernment/releases)

![image](https://user-images.githubusercontent.com/14230785/32886343-fbf346dc-caf2-11e7-8ae2-83235ef7b568.png)

**Comment by thehung** [comment]
Đã fix!
