### ISSUE TITLE
Lỗi: không xem trước được file pdf

### ISSUE THREAD

**Issue by ngocphan123** [nukeviet/eGovernment#62]
Trên trình duyệt chorme: (Cài đặt trên bản releases : https://github.com/nukeviet/eGovernment/releases)
- **Module văn bản không xem trước được file pdf như hình:**

![image](https://user-images.githubusercontent.com/14230785/32886955-f2c26ca8-caf4-11e7-8640-78ca8fca2171.png)

- **Module tin tức: Không hiển thị file đính kèm ngoài site tại chi tiết bài viết**

**Comment by hoaquynhtim99** [comment]
Vấn đề này đã được fix ở bản phát triển và sẽ cập nhật ở phiên bản tới
