### ISSUE TITLE
Lỗi khi tìm kiếm qua block tìm kiếm ở module opinions

### ISSUE THREAD

**Issue by thehung** [nukeviet/eGovernment#65]
Lỗi khi tìm kiếm qua block tìm kiếm ở module opinions. Hệ thống luôn báo là "Không có kết quả nào phù hợp với yêu cầu của bạn"
Phiên bản thử nghiệm: 97ebba4c60206b30918d03dda17b6a554b27c0a9

**Comment by vingheo** [comment]
Phiên bản thử nghiệm: 97ebba4
cái này chưa fix được hả anh

**Comment by hoaquynhtim99** [comment]
Lỗi này do block laws mặc định ô trạng thái để là Chưa thông qua nên nó chỉ tìm ở trạng thái chưa thông qua, đã sửa lại tại https://github.com/nukeviet/module-laws/commit/9e69f9a7f5312cb3ff71cd834d725426fe3f505b
