### ISSUE TITLE
Lỗi không hiển thị Ngày ban hành văn bản khi cấu hình

### ISSUE THREAD

**Issue by vingheo** [nukeviet/eGovernment#68]
khi cấu hình hiển thị thì không modun laws thì không hiển thị: 
Các văn bản cùng cơ quan ban hành; Các văn bản cùng lĩnh vực; Các văn bản cùng cơ quan ban hành

cài đặt trên localhost; phiên bản egov chính thức [1.05]
https://i.imgur.com/PccNCAd.jpg

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/nukeviet/module-laws/commit/b46021665eb9a8d441265208ce88429111b5e792
