### ISSUE TITLE
Lỗi khi nhấn cập nhật phiên bản

### ISSUE THREAD

**Issue by vingheo** [nukeviet/eGovernment#69]
Em cài xong NV egov chính thức 1.05: khi cài xong nhấn cập nhật phiên bản thì báo lỗi: "Hệ thống: Dữ liệu trả về không hợp chuẩn và Các ứng dụng: Dữ liệu trả về không hợp chuẩn." E cài trên localhost đê test

**Comment by thehung** [comment]
Bạn dùng phần mềm Vertrigo tạo môi trường localhost đúng ko?
Phần mềm này bị lỗi khi kết nối tới server của NukeViet. Cài trên hosting
thật sẽ không bị sao bạn nhé!

**Comment by vingheo** [comment]
Em dùng apache server

**Comment by hoaquynhtim99** [comment]
Hệ thống kiểm tra phiên bản của Egov đang được xây dựng nên phần đó chưa sử dụng được bạn

**Comment by hoaquynhtim99** [comment]
Hiện tại đã có thể kiểm tra phiên bản và cập nhật phiên bản cho Egov
