### ISSUE TITLE
Block "Văn bản mới" bị addon của FireFox là Avira Browser Safety chặn 

### ISSUE THREAD

**Issue by thehung** [nukeviet/eGovernment#7]
Nếu máy tính cài Avira thì block "văn bản mới" sẽ không hiển hoạt động do bị addon của FireFox là Avira Browser Safety coi là mã độc và chặn!
Phiên bản thử nghiệm: Bản mới nhất  tại thời điểm test.
Trình duyệt: FireFox 55 có addon Avira Browser Safety.

**Comment by vuthao** [comment]
anh @thehung kieemr tra lại dùm xem có bị lỗi đó không.

**Comment by thehung** [comment]
OK. Hết bị chặn rồi!
