### ISSUE TITLE
Lỗi module Tin tức: Phần đính kèm file trong chi tiết bài viết không hiển thị

### ISSUE THREAD

**Issue by thuvp1995** [nukeviet/eGovernment#71]
Sau khi module News có thêm chức năng đính kèm file và cập nhật cho egov thì ở themes egov chưa được cập nhật code. Vì vậy khi xem chi tiết bài viết ở egov bị thiếu mất file đính kèm.

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/eGovernment/commit/7772a28f7f815cfdc6a6ffc5192ed7208cb0b39d
