### ISSUE TITLE
Lỗi icon new không hiển thị khi thêm văn bản mới

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/eGovernment#74]
Khi thêm văn bản mới trong admin của module, nhưng tại block_new_law.tpl không xuất hiện icon new. Rất mong được hướng dẫn pix lỗi. Thank!

**Comment by thuvp1995** [comment]
hoanglongvnpt Mong bạn cung cấp thêm thông tin, nếu module văn bản của bạn đang cấu hình cho lấy ý kiến góp ý thì sẽ không có icon new hiện lên. Trường hợp không lấy ý kiến góp ý (tức module văn bản bình thường) mình test và thấy icon news vẫn hiển thị

**Comment by hoanglongvnpt** [comment]
Đây bạn
![vanban](https://user-images.githubusercontent.com/11238423/34433756-330ba8b2-ec36-11e7-9eaa-d200da9a411a.png)

**Comment by hoaquynhtim99** [comment]
Mình kiểm tra cũng không thấy lỗi này. Lưu ý cái icon nó tính dựa vào ngày ban hành văn bản chứ không phải ngày thêm văn bản.
@hoanglongvnpt kiểm tra lại nếu vẫn còn lỗi tạo Issue khác nhé
