### ISSUE TITLE
Lỗi modun tìm kiếm NV egov

### ISSUE THREAD

**Issue by vingheo** [nukeviet/eGovernment#77]
Khi mình gõ từ khóa vào khung tìm kiếm toàn site. Vẫn tìm kiếm thấy kết quả nhưng khi nhấp vào link thì chỉ hiệu quả với modun hệ thống như: tin tức, giới thiệu... Còn modun văn bản và lấy ý kiến người dân thì nhấp vào link không thấy kết quả.

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/nukeviet/module-laws/commit/b1cf6cd66943b8d34d2b68d9c10812176319e34b
