### ISSUE TITLE
Lỗi xóa (thay đổi) nhóm thành viên

### ISSUE THREAD

**Issue by vingheo** [nukeviet/eGovernment#81]
Mình đã tạo một số nhóm trong modun thành viên. Giờ mình đã đối tên, xóa nhóm: thực hiện tốt không có vấn đề gì cả. Lỗi ở đây là:
Khi mình kiểm tra lại: vẫn tồn tại tên nhóm lúc ban đầu: ở trong phần phân quyền (mặc dù nhóm đó đã bị xóa hoặc đã đổi tên).
VD: lúc đầu tên Nhóm A --> mình đổi tên nhóm A thành nhóm B (hoặc xóa nhóm A) --> Kiểm tra lại trong phân quyền vẫn tồn tại nhóm A (mặc dù nhóm A đã bị đổi tên hoặc xóa).

Mình dùng: egov 1.1 chạy trên localhost apache server

**Comment by hoaquynhtim99** [comment]
Cái này cần phải chỉ rõ "phần phân quyền" là phân quyền ở đâu? (module nào? khu vực nào của module đó)

**Comment by vingheo** [comment]
cảm ơn Anh vuthao. xóa cache của hệ thống là ok.

**Comment by hoaquynhtim99** [comment]
Theo nguyên tắc thì xóa nhóm cache của nhóm sẽ được tự xóa theo. Cái này nếu của hệ thống hoặc các module tích hợp sẵn trong egov thì phải xem lại module đó tự cache nhóm dẫn đến sai thông tin.

Nếu module tự viết thì chuyển cache về module users
