### ISSUE TITLE
Lỗi khi thêm file đính kèm trong module news

### ISSUE THREAD

**Issue by lyhuutrong** [nukeviet/eGovernment#82]
Ad ơi khi mình thêm nhiều file ảnh thì xuất hiện lỗi là ấn vào xem file hình ảnh thì nó không nằm giữa mà nhếch qua phải và che mất cái dấu X để tắt file hình rồi ạ. phải chỉnh chế độ màn hình 90% thì mới có thể thấy được dấu X và tắt ạ. Kể cả giao diện mobile cũng vậy nữa ạ.
Với mình có thêm ý kiến là module new cho đính kèm file thì nếu là file ảnh thì có thể cho thêm chế độ xem hình tiếp theo đi ạ.
Thanks các ad rất nhiều.

**Comment by hoaquynhtim99** [comment]
Mình kiểm tra không thấy lỗi đó bạn kiểm tra lại giao diện của mình, cung cấp thêm thông tin theo https://github.com/nukeviet/eGovernment/blob/develop/.github/ISSUE_TEMPLATE.md

Việc view slide show có liên quan đặc biệt đến giao diện cho nên nó sẽ không ưu tiên phát triển ở NukeViet mặc định
