### ISSUE TITLE
Dùng block html của module page không hiển thị code google

### ISSUE THREAD

**Issue by lyhuutrong** [nukeviet/eGovernment#83]
chào ban quản trị.
mong bqt giúp đỡ.
Dùng block html của module page không hiển thị code gôgle adsense nếu không hiển thị được thì mình cần phải làm gì để cho adsense hiển thị ngoài trang chủ và nằm giữa nội dung bài viết ạ. 
xin cảm ơn

**Comment by hoaquynhtim99** [comment]
Chào bạn, vấn đề này bạn lên diễn đàn https://nukeviet.vn/vi/forum/ để hỏi nhé. Đây là khu vực báo lỗi và thảo luận dành cho các nhà phát triển.
