### ISSUE TITLE
Lỗi khi thực hiện lệnh cài lại module news

### ISSUE THREAD

**Issue by thehung** [nukeviet/eGovernment#9]
Cài lại module news với Cơ sở dữ liệu mẫu thì ra trang trắng!

**Comment by vuthao** [comment]
@thehung trang trắng này ở đâu nhỉ, nếu ở trang chủ đã được sửa.
Nếu ở khu vực khác vui lòng chủ rõ khhu vực lỗi để tiện kiểm tra.

**Comment by vuthao** [comment]
Lỗi này đã được sủa, và sẽ được câp nhật vào phiên bản phát hành tới.
