### ISSUE TITLE
GÓP Ý - ĐIỀU CHỈNH LO GO KHỎI CHE  KHUẤT TIÊU ĐỀ BÀI VIẾT ĐẦU TIÊN - RSS

### ISSUE THREAD

**Issue by ntnhut79** [nukeviet/eGovernment#91]
Khi vào trang chủ chọn Sơ đồ cổng, nếu người dùng nhấn vào các module để truy cập bài viết, thì hiển thị lo go che lấp bài viết đầu tiên, như hình đính kèm, nhìn không hay
Đề xuất: điều chỉnh lo go co lại để không lấp bài viết.

http://egov-demo.nukeviet.vn/rss/tin-hoat-dong/
![hi n th lo go che khu t tieu d bai vi t - rss](https://user-images.githubusercontent.com/22661919/43353596-5fbece58-9266-11e8-8873-0a20bd3bc969.png)

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/47207961452c61ff22b7c79a8711b2cb0e6bba3f phần này sẽ được cập nhật ở phiên bản tiếp theo
