### ISSUE TITLE
LỖI KHÔNG UPLOAD FILE ẢNH - Cảnh báo "loại file không được phép tải lên"

### ISSUE THREAD

**Issue by ntnhut79** [nukeviet/eGovernment#92]
Vào module Tin tức, upload ảnh đại diện, sau khi tải lên 100% thì hiện một dấu chấm thang cảnh báo "loại file không được phép tải lên"hiện lên khoảng 02 s thì file mất đi.
Tên phiên bản: NukeViet eGovernment 1.1.01
Mã phiên bản: 1.1.01

**Comment by hoaquynhtim99** [comment]
Bạn khắc phục tạm thời bằng cách vào cấu hình Upload chỉnh Chunk Upload (Upload từng phần) về số 0. Vấn đề này đội code sẽ kiểm tra lại

**Comment by vingheo** [comment]
Mình cũng bị lỗi này, sau khi nâng cấp không upload được file

**Comment by lehuusonvptu** [comment]
Mình cũng bị sửa thế nào đây nhế hoaquynhtim99

**Comment by hoaquynhtim99** [comment]
@lehuusonvptu bạn không thấy comment đầu tiên của mình sao

**Comment by lehuusonvptu** [comment]
![1](https://user-images.githubusercontent.com/42171812/43820732-45f0a31c-9b11-11e8-8a2d-4fd1303671e3.png)
Vào phần này phải không. Đưa giá trị nào về 0

**Comment by hoaquynhtim99** [comment]
@lehuusonvptu thế cái gì đây bạn 
![08-08-2018 1-46-49 ch](https://user-images.githubusercontent.com/2421714/43820849-91f6eabe-9b11-11e8-8565-c1154af1de7e.jpg)

**Comment by lehuusonvptu** [comment]
Hichic Sửa trong code mình không thạo

**Comment by hoaquynhtim99** [comment]
@lehuusonvptu trong cái ảnh bạn gửi bạn không nhìn thấy cái chữ `Chunk Upload` sao? mình viết đúng tới mức viết hoa viết thường mà?

**Comment by lehuusonvptu** [comment]
OK cảm ơn bạn

**Comment by hoaquynhtim99** [comment]
Hiện vấn đề này đã fix trên NukeViet, đã cập nhật cho Egov trong lần phát hành tới

**Comment by hieukg0905** [comment]
em bị lỗi error: src refspec master does not match any khi up phai txt lên github thì xử lý sao v ạ
