### ISSUE TITLE
Sử dụng trình duyệt internet explorer

### ISSUE THREAD

**Issue by hvt10** [nukeviet/eGovernment#98]
Khi tôi dùng trình duyệt internet explorer để chạy http://liendoihoangvanthuquan10.com hay http://egov-demo.nukeviet.vn/ đều bị lỗi hình nền phía trên "che mất" menu.
Ở đây tôi không biết chèn file lỗi ở đâu...
Xin các bạn xem lại giúp nhé!

**Comment by vuthao** [comment]
@hvt10 bạn xem lại Quy định thông báo lỗi: https://github.com/nukeviet/eGovernment/blob/develop/.github/ISSUE_TEMPLATE.md để chúng tôi có thể kiểm tra và sửa nhanh nhất.

**Comment by hoaquynhtim99** [comment]
Lỗi đã sửa ở commit trên, bạn có thể tải https://raw.githubusercontent.com/nukeviet/eGovernment/f1bc93e35be84b97f570a8ef116fbba5ceaf5584/themes/egov/css/custom.css để ghi đè
