### ISSUE TITLE
Lỗi truy cập

### ISSUE THREAD

**Issue by thcsphc** [nukeviet/eGovernment#99]
Mình vừa cài xong nukeviet 4.3.07 trên hosting thông qua Cpanel. Ccas mục cài đặt thành coog tuy nhiên sau khi ấn vào đăng nhập qoản trị hoặc vào Site thì báo lỗi này: **Session object not supported
Mong các bạn chỉ giáo.**
http://thcsphanhuychu.edu.vn/index.php

**Comment by hoaquynhtim99** [comment]
phần này do máy chủ của bạn, giờ chắc bạn cũng đã khắc phục được rồi.
